name: Build Project Docker Image
description: Build application docker image
inputs:
  path_dockerfile:
    description: "Path to the Dockerfile"
  image_name:
    description: "Docker image name"
  tag_name:
    description: "Docker image tag"
runs:
  using: composite
  steps:
    - name: Define tag name
      run:  |
        if [ -z "${{ inputs.input-name }}" ]; then
            echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
            echo "TAG=${{ inputs.input-name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Define image name
      run: echo "DOCKER_IMAGE_NAME=${{ inputs.image_name }}:${{ env.TAG }}" >> $GITHUB_ENV
      shell: bash

    - name: Build the app docker image
      run: docker build . --file ${{ inputs.path_dockerfile }} --tag ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash

    - name: List docker images
      run: docker images
      shell: bash