name: Push to Docker Hub
description: Push project image to Docker Hub
inputs:
  docker_username:
    description: "Docker username"
  docker_token:
    description: "Docker token"
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}

    - name: Push docker image to Docker Hub
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash