name: Push to Docker Hub
description: Push project image to Docker Hub
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push docker image to Docker Hub
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}
      shell: bash