# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: leojgpereira/academy/.github/actions/maven_build@main
    - uses: leojgpereira/academy/.github/actions/docker_build@main
      with:
        path_dockerfile: src/main/docker/Dockerfile.jvm
        image_name: leandropereira057/academy
        tag_name: v1
    - uses: leojgpereira/academy/.github/actions/docker_push@main
      with:
        docker_username: ${{ vars.DOCKERHUB_USERNAME }}
        docker_token: ${{ secrets.DOCKERHUB_TOKEN  }}